apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: complaint-intelligence-app
  namespace: complaint-intelligence
spec:
  to:
    kind: Service
    name: complaint-intelligence-app
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
