apiVersion: v1
kind: Namespace
metadata:
  name: complaint-intelligence
  labels:
    opendatahub.io/dashboard: "true"
    modelmesh-enabled: "false"
  annotations:
    openshift.io/display-name: "Complaint Intelligence (UC02)"
