apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: uc02-storage
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: https://github.com/Deim0s13/rhoai.git
    targetRevision: main
    path: 02-complaint-intelligence/manifests/storage
  destination:
    server: https://kubernetes.default.svc
    namespace: complaint-intelligence
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
